name: Check Appointment Availability

on:
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-availability:
    name: Check for available dates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0

      - name: Run test suite
        id: tests
        continue-on-error: true
        run: |
          OUTPUT=$(inso run test "vapt-vupt-spec" --ci)
          echo "$OUTPUT" > test_output.txt
          echo "::set-output name=test_output::$OUTPUT"
          if echo "$OUTPUT" | grep -q "fail"; then
            echo "::set-output name=status::failure"
          else
            echo "::set-output name=status::success"
          fi

      - name: Send Discord notification
        if: success() || failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          if [ "${{ steps.tests.outputs.status }}" = "success" ]; then
            MESSAGE_TITLE="✅ Available Dates Found!"
            COLOR="65280"
          else
            MESSAGE_TITLE="❌ No Available Dates"
            COLOR="16711680"
          fi
          
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          TEST_OUTPUT=$(cat test_output.txt)
          
          # Escape test output for JSON
          TEST_OUTPUT=$(echo "$TEST_OUTPUT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          payload=$(cat <<EOF
          {
            "embeds": [{
              "title": "$MESSAGE_TITLE",
              "description": "\`\`\`$TEST_OUTPUT\`\`\`",
              "color": $COLOR,
              "footer": {
                "text": "Check ran at $CURRENT_TIME"
              }
            }]
          }
          EOF
          )
          
          curl -H "Content-Type: application/json" \
          -d "$payload" \
          $DISCORD_WEBHOOK