name: Scheduled Availability Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.1
          wrapper: true
      
      - name: Run Tests
        id: run_tests
        run: inso run test "vapt-vupt-spec" --src ./specs/vapt.json
        continue-on-error: true

      - name: Send Discord notification
        if: success() || failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Get test results from previous step
          TEST_OUTPUT="${{ steps.run_tests.outputs.stdout }}"
          TEST_ERROR="${{ steps.run_tests.outputs.stderr }}"
          EXIT_CODE="${{ steps.run_tests.outcome }}"
          
          if [ "$EXIT_CODE" = "success" ]; then
            MESSAGE_TITLE="✅ Available Dates Found!"
            COLOR="65280"  # Green
          else
            MESSAGE_TITLE="❌ No Available Dates"
            COLOR="16711680"  # Red
          fi
          
          CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          
          # Combine stdout and stderr for complete output
          FULL_OUTPUT="STDOUT:\n${TEST_OUTPUT}\n\nSTDERR:\n${TEST_ERROR}"
          
          # Escape special characters for JSON
          ESCAPED_OUTPUT=$(echo "$FULL_OUTPUT" | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          payload=$(cat <<EOF
          {
            "embeds": [{
              "title": "$MESSAGE_TITLE",
              "description": "\`\`\`\n$ESCAPED_OUTPUT\`\`\`",
              "color": $COLOR,
              "footer": {
                "text": "Check ran at $CURRENT_TIME"
              }
            }]
          }
EOF
          )
          
          # Send to Discord
          curl -H "Content-Type: application/json" \
          -d "$payload" \
          $DISCORD_WEBHOOK