name: Scheduled Availability Check

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-availability:
    runs-on: ubuntu-latest
    continue-on-error: true   # Allows the job to "soft-fail"
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.1
          wrapper: true

      - name: Run test suites
        id: run_tests              # Add an ID to reference outputs if needed
        run: inso run test \"New Suite\" --ci -w ./specs/vapt.json --env \"Base Environment\"
      
      # Run only if "Run test suites" step is successful
      - name: Discord notification
        if: success()              # Runs only if previous steps succeed
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Appointment Checker"
          DISCORD_AVATAR: "https://github.com/github.png"
          DISCORD_EMBEDS: |
            [
              {
                "title": "✅ Available Dates Found!",
                "description": "<@181270590672338944> ```\n${{ steps.run_tests.outputs.stdout }}```",
                "color": 65280,
                "footer": {
                  "text": "Check ran at ${{ github.event.schedule || 'Manual Trigger' }}"
                }
              }
            ]
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Appointment availability check completed"
