name: Scheduled Availability Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Setup Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.1
          wrapper: true
      
      - name: Run test suites
        run: ls -laR && inso run test \"New Suite\" --ci --env \"Base Environment\"

# only run if the previous step was successful
      - name: Discord notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Appointment Checker"
          DISCORD_AVATAR: "https://github.com/github.png"
          DISCORD_EMBEDS: |
            [
              {
                "title": "✅ Available Dates Found!",
                "description": "```\n${{ steps.run_tests.outputs.stdout }}```",
                "color": 65280,
                "footer": {
                  "text": "Check ran at ${{ github.event.schedule || 'Manual Trigger' }}"
                }
              }
            ]
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Appointment availability check completed"
