name: Scheduled Availability Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */1 * * *'  # Runs every hour
  workflow_dispatch:        # Allows manual trigger

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Inso CLI
        uses: kong/setup-inso@v1
        with:
          inso-version: 10.1.1
          wrapper: true
      
      - name: Run Tests
        id: run_tests
        run: |
          inso run test > test_output.log 2>&1
          echo "::set-output name=stdout::$(cat test_output.log)"
        continue-on-error: false  # Ensures workflow stops on failure

      - name: Discord notification
        if: success()  # Runs only if the tests passed
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Appointment Checker"
          DISCORD_AVATAR: "https://github.com/github.png"
          DISCORD_EMBEDS: |
            [
              {
                "title": "✅ Available Dates Found!",
                "description": "```\n${{ steps.run_tests.outputs.stdout }}```",
                "color": 65280,
                "footer": {
                  "text": "Check ran at ${{ github.event.schedule || 'Manual Trigger' }}"
                }
              }
            ]
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Appointment availability check completed"
